export const GAMES = [
    'Age of Empires',
    'Apex Legends',
    'Arena of Valor',
    'Brawl Stars',
    'Brawlhalla',
    'Call of Duty',
    'Chess',
    'Clash Royale',
    'Counter-Strike',
    'Deadlock',
    'Diablo',
    'Dota',
    'EA Sports FC',
    'Fatal Fury',
    'Fortnite',
    'Free Fire',
    'Geoguessr',
    'Gran Turismo',
    'Guilty Gear',
    'Halo',
    'Hearthstone',
    'Honor of Kings',
    'iRacing',
    'League of Legends',
    'Magic: The Gathering',
    'Marvel Rivals',
    'Mobile Legends: Bang Bang',
    'Mortal Kombat',
    'NBA 2K',
    'Omega Strikers',
    'Overwatch',
    'PUBG',
    'Pokemon Unite',
    'Pokemon VGC',
    'Quake',
    'Rainbow Six Siege',
    'Rocket League',
    'Splatoon',
    'StarCraft',
    'Street Fighter',
    'Super Smash Bros.',
    'Teamfight Tactics',
    'Tekken',
    'The Finals',
    'Trackmania',
    'Valorant',
    'Warcraft',
    'World of Tanks',
    'World of Warcraft',
    'Yu-Gi-Oh!',
];
